### ISSUE TITLE
"TypeError: string indices must be integers" when using predefined colormaps

### ISSUE THREAD

**Issue by Akronix** [cokelaer/colormap#10]
Hello. I have this code:
```
from colormap import Colormap
c = Colormap()
mycmap = c.cmap('YlGnBu')
```
When I run that, I get the following error on the last line:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akronix/.pyenv/versions/wikichron/lib/python3.6/site-packages/colormap/colors.py", line 860, in cmap
    index = np.linspace(0, 1, len(colors['red']))
TypeError: string indices must be integers
```

However, it does work if I create a colormap with key RGB values:

```
from colormap import Colormap
c = Colormap() 
mycmap = c.cmap( {'red':[1,1,0], 'green':[0,1,.39], 'blue':[0,1,0]}) 
```

The versions I'm using of the related packages are:
```
colormap==1.0.2
numpy==1.17.2
```

Any idea how to fix it or why I'm getting this error while other people are not?

**Comment by Akronix** [comment]
Hi. I found a workaround to the issue.

The error get solved if you install the "tkinter" package (which apparently, comes by default in Windows, but not in Ubuntu). To install in Ubuntu, you need to use apt-get or [use this solution from SO](https://stackoverflow.com/a/45622282/2904315) if you, as I am, are using pyenv.

However, I don't fully understand why tkinter is so relevant here and, more striking, why there's no a proper error message indicating this as there is for test_colormap().

Tell me if I can help with this somehow.

**Comment by cokelaer** [comment]
closing due to lack of activity/develop,ent and a solution was found in another package. Wont't fix. Thanks for reporting this issue tough
