### ISSUE TITLE
name provided nipy_spectral is not recognised when trying to build for Python 3.8

### ISSUE THREAD

**Issue by tillea** [cokelaer/colormap#11]
Hi,
Debian is moving to Python3.8 and I'm trying to update the Debian package of colormap.  Unfortunately I get a build time test error:

    test_get_cmap.test_get_cmap ... ERROR

    ======================================================================
    ERROR: test_get_cmap.test_get_cmap
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/build/python-colormap-1.0.2/.pybuild/cpython3_3.8_colormap/build/test/test_get_cmap.py", line 7, in test_get_cmap
        get_cmap("nipy_spectral")
      File "/build/python-colormap-1.0.2/.pybuild/cpython3_3.8_colormap/build/colormap/get_cmap.py", line 57, in cmap_builder
        raise ValueError(txt)
    ValueError: name provided nipy_spectral is not recognised.
     valid name can be found in colormap.colormap_names

    ----------------------------------------------------------------------
    Ran 13 tests in 0.168s

    FAILED (errors=1)

Any idea how to fix this?
BTW, it would help if you would tag colormap releases also on Github (not only on PyPI).
Kind regards; Andreas.

**Comment by cokelaer** [comment]
problaby obsolete error. Closing for now
