### ISSUE TITLE
Required module easydev not installed through pip

### ISSUE THREAD

**Issue by bersbersbers** [cokelaer/colormap#17]
```
$ pip install colormap
$ python3
```

```
>>> import colormap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bers/.local/lib/python3.8/site-packages/colormap/__init__.py", line 31, in <module>
    from . import colors
  File "/home/bers/.local/lib/python3.8/site-packages/colormap/colors.py", line 26, in <module>
    from easydev.tools import check_param_in_list, swapdict, check_range
ModuleNotFoundError: No module named 'easydev'
```

**Comment by cokelaer** [comment]
wierd. Are you using a conda environment  ? how did you install the package ? thanks

**Comment by cokelaer** [comment]
I removed easydev as a dependency
